spring:
  application:
    name: mall-member
  datasource:
    username: root
    password: root@hiekn
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.4.151:3306/rs_ums?serverTimezone=Asia/Shanghai

server:
  port: 9002
